pub mod seq;
pub mod smallvec;
pub mod map;
pub mod slotmap;
pub mod bitset;
pub mod permutation;
pub mod graph;
pub mod viz;
pub mod parse;
pub mod iso;
pub mod enumeration;
pub mod random;
pub mod embedding;
pub mod planar;
pub mod planar_old;
pub mod toroidal;
pub mod prelude;

//pub use graph::Graph16;
